name: Deploy Webapp to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'

    - name: Build Webapp
      run: |
        cd Webapp
        dotnet publish Webapp.csproj -c Release -o ./publish

    - name: Copy Files to Azure VM
      uses: appleboy/scp-action@v0.1.10 # Versión actualizada
      with:
        host: 52.169.18.180 # Reemplaza con la IP de tu VM
        username: azureuser
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        source: ./Webapp/publish/
        target: /var/www/webapp

    - name: Restart Application on Azure VM
      uses: appleboy/ssh-action@v0.1.10 # Versión actualizada
      with:
        host: 52.169.18.180 # Reemplaza con la IP de tu VM
        username: azureuser
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        script: |
          sudo systemctl restart kestrel-webapp.service
